#!/usr/bin/env python3
"""Generate asm/aarch64/defs.inc: the engine's shared constants and struc
layouts, converted from the NASM sources to GNU as `.equ`s.

Covers every top-level `%define NAME value` (constants only, not register
aliases or macro-local defines) and every `struc` in lib.asm, rt/, utils/,
engine/ and effects/ids.inc, in include order, so the aarch64 files can use
the same names as the x86 ones. Effects keep their own constants in their
own files. Rerun after changing a constant on the x86 side.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
ASM = ROOT / "asm"
ORDER = [
    "ttfx.inc", "effects/ids.inc", "lib.asm", "rt/sys.asm", "utils/rng.asm",
    "utils/graphics.asm", "utils/pycompat.asm", "utils/geometry.asm",
    "utils/color.asm", "utils/hexterm.asm", "utils/easing.asm",
    "engine/visual.asm", "engine/chars.asm", "engine/input.asm",
    "engine/terminal.asm", "engine/scene.asm", "engine/events.asm",
    "engine/motion.asm", "engine/update.asm", "engine/particles.asm",
    "engine/render.asm", "utils/spanning_tree.asm",
]
REGS = set(
    "rax rbx rcx rdx rsi rdi rbp rsp eax ebx ecx edx esi edi ebp esp al bl cl dl"
    " sil dil ax bx cx dx".split()
) | {f"r{i}{s}" for i in range(8, 16) for s in ("", "d", "w", "b")} | {
    f"{p}mm{i}" for p in "xyz" for i in range(32)}
SIZES = {"resb": 1, "resw": 2, "resd": 4, "resq": 8, "resy": 32, "resz": 64, "reso": 16}
SKIP = {"TIER", "TTFX_INC"}


def expr(text):
    text = text.split(";")[0].strip()
    text = re.sub(r"__float64__\(([^)]*)\)", lambda m: float_bits(m.group(1)), text)
    return text


def float_bits(lit):
    import struct
    return hex(struct.unpack("<Q", struct.pack("<d", float(lit)))[0])


def main():
    out = ["// defs.inc - GENERATED by tools/asm/aarch64/gen_defs.py from the x86",
           "// NASM sources: every shared %define constant and struc layout, as",
           "// .equ. Do not edit; rerun the generator.", ""]
    seen = {}
    for rel in ORDER:
        path = ASM / rel
        lines = path.read_text().splitlines()
        out.append(f"// ---- {rel}")
        depth = 0          # inside %macro
        cond = []          # %if stack: True when the branch is taken
        struc = None
        for raw in lines:
            line = raw.strip()
            if line.startswith("%macro"):
                depth += 1
                continue
            if line.startswith("%endmacro"):
                depth -= 1
                continue
            if depth:
                continue
            m = re.match(r"%if\s+TIER\s*(>=|==|<|>)\s*(\d)", line)
            if m:
                op, n = m.groups()
                cond.append(eval(f"1 {op} {n}"))  # the TIER 1 path
                continue
            if re.match(r"%if|%ifdef|%ifndef", line):
                cond.append(None)
                continue
            if line.startswith("%else") and cond:
                if cond[-1] is not None:
                    cond[-1] = not cond[-1]
                continue
            if line.startswith("%endif") and cond:
                cond.pop()
                continue
            if any(c is False for c in cond):
                continue
            m = re.match(r"struc\s+(\S+)", line)
            if m:
                struc = [m.group(1), 0]
                continue
            if line.startswith("endstruc") and struc:
                out.append(f".equ {struc[0]}_size, {struc[1]}")
                seen[f"{struc[0]}_size"] = struc[1]
                struc = None
                continue
            if struc:
                m = re.match(r"(\.\w+)\s*:?\s*(res[bwdqyzo])\s+(.+)", line)
                if m:
                    name, kind, count = m.groups()
                    count = expr(count)
                    out.append(f".equ {struc[0]}{name}, {struc[1]}")
                    # sizes may reference other strucs' _size: evaluate via the
                    # already-emitted ones
                    try:
                        n = eval(count, {}, {k: v for k, v in seen.items()})
                    except Exception:
                        sys.exit(f"{rel}: cannot size {line!r}")
                    struc[1] += SIZES[kind] * int(n)
                    seen[f"{struc[0]}{name}".replace(".", "_")] = struc[1]
                    continue
                continue
            m = re.match(r"%define\s+(\w+)\s+(.+)", line)
            if not m:
                continue
            name, value = m.groups()
            value = expr(value)
            if name in SKIP or name.startswith("SYS_") or value.split()[0] in REGS or not value:
                continue
            if name in seen and seen[name] != value:
                print(f"note: {name} redefined in {rel}: {seen[name]} -> {value}", file=sys.stderr)
            out.append(f".equ {name}, {value}")
            try:
                seen[name] = eval(value.replace("~", "-1-"), {}, dict(seen))
            except Exception:
                seen[name] = value
        # struc _size values for later sizing
        for l in out:
            m = re.match(r"\.equ (\w+)_size, (\d+)", l)
            if m:
                seen[m.group(1) + "_size"] = int(m.group(2))
    (ASM / "aarch64" / "defs.inc").write_text("\n".join(out) + "\n")


main()
